/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCarcel;

import carcelConsola.Administrativo;
import controlador.ControladorSistema;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yo
 */
public class Administrativos extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Administrativos
     */
    public Administrativos() {
        this.setContentPane(fondo);
        initComponents();
        cargarTablaReclusos(ControladorSistema.operaciones.getListaAdmin());
        lblCiAdmin.setVisible(false);
        txtCiAdmin.setVisible(false);
        lblTurnoActual.setVisible(false);
        txtTurnoActual.setVisible(false);

        lblNuevoTurno.setVisible(false);
        txtNuevoTurno.setVisible(false);

        btnConfirmarTurno.setVisible(false);
    }

    private void cargarTablaReclusos(List<Administrativo> lista) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI");
        modelo.addColumn("Tipo");
        modelo.addColumn("Turno");
        modelo.addColumn("Sueldo");

        for (Administrativo a : lista) {
            modelo.addRow(new Object[]{
                a.getNombre(),
                a.getEdad(),
                a.getCi(),
                a.getTipo(),
                a.getTurno(),
                a.getSueldo()
            });
        }
        tablaAdministrativos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdministrativos = new javax.swing.JTable();
        mostrarTodosBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCiPagar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPagarSueldo = new javax.swing.JButton();
        msjLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCiDespedir = new javax.swing.JTextField();
        btnDespedir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblTurnoActual = new javax.swing.JLabel();
        lblNuevoTurno = new javax.swing.JLabel();
        txtTurnoActual = new javax.swing.JTextField();
        txtNuevoTurno = new javax.swing.JTextField();
        btnConfirmarTurno = new javax.swing.JButton();
        lblCiAdmin = new javax.swing.JLabel();
        txtCiAdmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LISTA DE ADMINISTRATIVOS");

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaAdministrativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Edad", "CI.", "Tipo", "Turno", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(tablaAdministrativos);

        mostrarTodosBtn.setText("ACTUALIZAR");
        mostrarTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosBtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("CI. :");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Boleta de Sueldo por Nro. CI.");

        btnPagarSueldo.setText("BOLETA");
        btnPagarSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarSueldoActionPerformed(evt);
            }
        });

        msjLabel.setForeground(new java.awt.Color(255, 0, 0));
        msjLabel.setText("jLabel4");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Despedir Adm. por Nro. CI.");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("CI. :");

        btnDespedir.setText("DESPEDIR");
        btnDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespedirActionPerformed(evt);
            }
        });

        jButton1.setText("CAMBIAR TURNO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTurnoActual.setForeground(new java.awt.Color(255, 0, 0));
        lblTurnoActual.setText("Turno actual:");

        lblNuevoTurno.setForeground(new java.awt.Color(255, 0, 0));
        lblNuevoTurno.setText("Nuevo turno: ");

        txtTurnoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurnoActualActionPerformed(evt);
            }
        });

        btnConfirmarTurno.setText("REALIZAR CAMBIO");
        btnConfirmarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTurnoActionPerformed(evt);
            }
        });

        lblCiAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblCiAdmin.setText("CI. Administrativo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNuevoTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTurnoActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCiAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTurnoActual)
                            .addComponent(txtNuevoTurno)
                            .addComponent(txtCiAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(btnConfirmarTurno)
                        .addGap(156, 156, 156))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolver)
                                .addGap(183, 183, 183)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(mostrarTodosBtn)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnDespedir)
                                                    .addComponent(txtCiDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(188, 188, 188))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPagarSueldo)
                                            .addComponent(txtCiPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(jLabel1)
                    .addComponent(mostrarTodosBtn))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCiPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCiDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagarSueldo)
                    .addComponent(btnDespedir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCiAdmin)
                            .addComponent(txtCiAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTurnoActual)
                            .addComponent(txtTurnoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNuevoTurno)
                            .addComponent(txtNuevoTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarTurno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msjLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void mostrarTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosBtnActionPerformed
        // TODO add your handling code here:
        lblCiAdmin.setVisible(false);
        txtCiAdmin.setVisible(false);
        lblTurnoActual.setVisible(false);
        txtTurnoActual.setVisible(false);

        lblNuevoTurno.setVisible(false);
        txtNuevoTurno.setVisible(false);

        btnConfirmarTurno.setVisible(false);

        msjLabel.setText("");
        txtCiPagar.setText("");
        txtCiDespedir.setText("");

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI");
        modelo.addColumn("Tipo");
        modelo.addColumn("Turno");
        modelo.addColumn("Sueldo");

        for (Administrativo a : ControladorSistema.operaciones.getListaAdmin()) {
            Object[] fila = {
                a.getNombre(), a.getEdad(), a.getCi(),
                a.getTipo(), a.getTurno(), a.getSueldo()
            };
            modelo.addRow(fila);
        }

        tablaAdministrativos.setModel(modelo);


    }//GEN-LAST:event_mostrarTodosBtnActionPerformed

    private void btnPagarSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarSueldoActionPerformed
        // TODO add your handling code here:
        String ci = txtCiPagar.getText();
        int sw = 0;
        double bono = 0;
        msjLabel.setText("");

        for (Administrativo a : ControladorSistema.operaciones.getListaAdmin()) {
            if (a.getCi().equalsIgnoreCase(ci)) {
                sw = 1;

                double total = a.getSueldo();

                if (a.getTurno().equalsIgnoreCase("noche")) {
                    //se da un bono del 20% por turnos noche
                    bono = a.getSueldo() * 0.20;
                    total = total + bono;
                }
                if (bono > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Administrativo: " + a.getNombre() + "\n"
                            + "Sueldo base: " + a.getSueldo() + "\n"
                            + "Bono: " + bono + " por trabajo noche \n"
                            + "Sueldo total: " + total);
                    break;
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Administrativo: " + a.getNombre() + "\n"
                            + "Sueldo base: " + a.getSueldo() + "\n"
                            + "Bono: Sin Bono Extra \n"
                            + "Sueldo total: " + a.getSueldo());
                    break;
                }

            }
        }
        if (sw == 0) {
            msjLabel.setText("No se Econtro Nro. de CI");
        }


    }//GEN-LAST:event_btnPagarSueldoActionPerformed

    private void btnDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespedirActionPerformed
        // TODO add your handling code here:
        String ci = txtCiDespedir.getText();
        int sw = 0;
        msjLabel.setText("");

        for (Administrativo a : ControladorSistema.operaciones.getListaAdmin()) {
            if (a.getCi().equalsIgnoreCase(ci)) {
                sw = 1;
                int confirm = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de despedir a " + a.getNombre() + "?",
                        "Confirmar", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    ControladorSistema.operaciones.getListaAdmin().remove(a);
                    msjLabel.setText("Administrativo despedido");
                    mostrarTodosBtnActionPerformed(null); // refrescar tabla
                } else {
                    msjLabel.setText("Operacion Cancelada");
                }
                break;
            }
        }
        if (sw == 0) {
            msjLabel.setText("No se encontro Nro. de Ci");
        }

    }//GEN-LAST:event_btnDespedirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lblCiAdmin.setVisible(true);
        txtCiAdmin.setVisible(true);
        lblTurnoActual.setVisible(true);
        txtTurnoActual.setVisible(true);

        lblNuevoTurno.setVisible(true);
        txtNuevoTurno.setVisible(true);

        btnConfirmarTurno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTurnoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurnoActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurnoActualActionPerformed

    private void btnConfirmarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTurnoActionPerformed
        // TODO add your handling code here:
        String ci = txtCiAdmin.getText();
        String turnoActual = txtTurnoActual.getText();
        String nuevoTurno = txtNuevoTurno.getText();

        int sw = 0;

        for (Administrativo a : ControladorSistema.operaciones.getListaAdmin()) {

            if (a.getCi().equalsIgnoreCase(ci)) {

                sw = 1;

                a.setTurno(nuevoTurno);

                msjLabel.setText("Turno cambiado correctamente");
                cargarTablaReclusos(
                        ControladorSistema.operaciones.getListaAdmin()
                );
                break;
            }
        }

        if (sw == 0) {
            msjLabel.setText("No se encontró el CI");
        }

        
    }//GEN-LAST:event_btnConfirmarTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrativos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarTurno;
    private javax.swing.JButton btnDespedir;
    private javax.swing.JButton btnPagarSueldo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCiAdmin;
    private javax.swing.JLabel lblNuevoTurno;
    private javax.swing.JLabel lblTurnoActual;
    private javax.swing.JButton mostrarTodosBtn;
    private javax.swing.JLabel msjLabel;
    private javax.swing.JTable tablaAdministrativos;
    private javax.swing.JTextField txtCiAdmin;
    private javax.swing.JTextField txtCiDespedir;
    private javax.swing.JTextField txtCiPagar;
    private javax.swing.JTextField txtNuevoTurno;
    private javax.swing.JTextField txtTurnoActual;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/admin2.jfif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
