/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCarcel;

import carcelConsola.Recluso;
import controlador.ControladorSistema;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yo
 */
public class Reclusos extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    
    
    /**
     * Creates new form Reclusos
     */
    public Reclusos() {
        this.setContentPane(fondo);
        initComponents();
        //llamamos al controlador donde estan guardado las operaciones y la lista
        cargarTablaReclusos(ControladorSistema.operaciones.getListaRecluso());
        lblCeldaActual.setVisible(false);
        txtCeldaActual.setVisible(false);
        lblNuevaCelda.setVisible(false);
        txtNuevaCelda.setVisible(false);
        CambiarCeldaBtn.setVisible(false);
    }

    //metodo para crear la tabla
    private void cargarTablaReclusos(List<Recluso> lista) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI.");
        modelo.addColumn("Delito");
        modelo.addColumn("Condena");
        modelo.addColumn("Nro. Celda");
        //aca en este forsito recoge todos lo datos y lo lleva a la tabla 
        for (Recluso r : lista) {
            modelo.addRow(new Object[]{
                r.getNombre(),
                r.getEdad(),
                r.getCi(),
                r.getDelito(),
                r.getCondena(),
                r.getNroCelda()
            });
        }
        tablaReclusos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReclusos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarCelda = new javax.swing.JTextField();
        btnBuscarCelda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarDelito = new javax.swing.JTextField();
        btnBuscarDelito = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        msjLable = new javax.swing.JLabel();
        btnCambiaCelda = new javax.swing.JButton();
        lblCeldaActual = new javax.swing.JLabel();
        txtCeldaActual = new javax.swing.JTextField();
        lblNuevaCelda = new javax.swing.JLabel();
        txtNuevaCelda = new javax.swing.JTextField();
        CambiarCeldaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("            LISTA DE RECLUSOS");

        tablaReclusos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Edad", "CI.", "Delito", "Condena", "N°"
            }
        ));
        jScrollPane1.setViewportView(tablaReclusos);

        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Buscar por Nro. Celda");

        btnBuscarCelda.setText("BUSCAR");
        btnBuscarCelda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCeldaActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Buscar por Delito");

        btnBuscarDelito.setText("BUSCAR");
        btnBuscarDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDelitoActionPerformed(evt);
            }
        });

        btnMostrarTodos.setText("ACTUALIZAR");
        btnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosActionPerformed(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        msjLable.setForeground(new java.awt.Color(102, 255, 255));
        msjLable.setText("jLabel4");

        btnCambiaCelda.setText("CAMBIAR DE CELDA");
        btnCambiaCelda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiaCeldaActionPerformed(evt);
            }
        });

        lblCeldaActual.setForeground(new java.awt.Color(102, 255, 255));
        lblCeldaActual.setText("Digite el numero de celda actual:");

        txtCeldaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCeldaActualActionPerformed(evt);
            }
        });

        lblNuevaCelda.setForeground(new java.awt.Color(102, 255, 255));
        lblNuevaCelda.setText("Nueva celda:");

        CambiarCeldaBtn.setText("REALIZAR CAMBIO DE CELDA");
        CambiarCeldaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarCeldaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarCelda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarCelda))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarDelito)
                                    .addComponent(txtBuscarDelito, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(139, 139, 139))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(158, 158, 158)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarTodos)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCambiaCelda)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNuevaCelda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCeldaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(msjLable, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CambiarCeldaBtn)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNuevaCelda)
                                            .addComponent(txtCeldaActual))
                                        .addGap(119, 119, 119)))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnVolver)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnMostrarTodos)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarCelda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscarDelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCelda)
                    .addComponent(btnBuscarDelito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiaCelda)
                    .addComponent(lblCeldaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCeldaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevaCelda)
                    .addComponent(txtNuevaCelda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(msjLable)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CambiarCeldaBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarCeldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCeldaActionPerformed
        // TODO add your handling code here:
        int sw = 0;
        String celdaBuscada = txtBuscarCelda.getText();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI.");
        modelo.addColumn("Delito");
        modelo.addColumn("Condena");
        modelo.addColumn("Nro. Celda");

        for (Recluso r : ControladorSistema.operaciones.getListaRecluso()) {
            if (r.getNroCelda().equalsIgnoreCase(celdaBuscada)) {
                sw = 1;
                Object[] fila = {
                    r.getNombre(), r.getEdad(), r.getCi(),
                    r.getDelito(), r.getCondena(), r.getNroCelda()
                };
                modelo.addRow(fila);
            }
        }

        if (sw == 0) {
            msjLable.setText("No se encontro ningun recluso");
        } else {
            tablaReclusos.setModel(modelo);
            msjLable.setText("");
        }

    }//GEN-LAST:event_btnBuscarCeldaActionPerformed

    private void btnBuscarDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDelitoActionPerformed
        // TODO add your handling code here:
        int sw = 0;
        String delitoBuscado = txtBuscarDelito.getText();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI.");
        modelo.addColumn("Delito");
        modelo.addColumn("Condena");
        modelo.addColumn("Nro. Celda");

        for (Recluso r : ControladorSistema.operaciones.getListaRecluso()) {
            if (r.getDelito().equalsIgnoreCase(delitoBuscado)) {
                sw = 1;
                Object[] fila = {
                    r.getNombre(), r.getEdad(), r.getCi(),
                    r.getDelito(), r.getCondena(), r.getNroCelda()
                };
                modelo.addRow(fila);
            }
        }

        if (sw == 0) {
            msjLable.setText("No se encontro ningun recluso con ese delito");
        } else {
            tablaReclusos.setModel(modelo);
            msjLable.setText("");
        }


    }//GEN-LAST:event_btnBuscarDelitoActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed
        // TODO add your handling code here:
        //actualiza la tabla
        lblCeldaActual.setVisible(false);
        txtCeldaActual.setVisible(false);
        lblNuevaCelda.setVisible(false);
        txtNuevaCelda.setVisible(false);
        CambiarCeldaBtn.setVisible(false);

        msjLable.setText("");
        txtBuscarCelda.setText("");
        txtBuscarDelito.setText("");

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI.");
        modelo.addColumn("Delito");
        modelo.addColumn("Condena");
        modelo.addColumn("Nro. Celda");

        for (Recluso r : ControladorSistema.operaciones.getListaRecluso()) {
            Object[] fila = {
                r.getNombre(), r.getEdad(), r.getCi(),
                r.getDelito(), r.getCondena(), r.getNroCelda()
            };
            modelo.addRow(fila);
        }
        tablaReclusos.setModel(modelo);

    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnCambiaCeldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiaCeldaActionPerformed
        // TODO add your handling code here:
        lblCeldaActual.setVisible(true);
        txtCeldaActual.setVisible(true);
        lblNuevaCelda.setVisible(true);
        txtNuevaCelda.setVisible(true);
        CambiarCeldaBtn.setVisible(true);
    }//GEN-LAST:event_btnCambiaCeldaActionPerformed

    private void txtCeldaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCeldaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCeldaActualActionPerformed

    private void CambiarCeldaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarCeldaBtnActionPerformed
        // TODO add your handling code here:
        String celdaActual = txtCeldaActual.getText();
        String nuevaCelda = txtNuevaCelda.getText();

        int sw = 0;

        for (Recluso r : ControladorSistema.operaciones.getListaRecluso()) {

            if (r.getNroCelda().equals(celdaActual)) {

                sw = 1;
                r.setNroCelda(nuevaCelda);

                msjLable.setText("Celda cambiada correctamente");
                cargarTablaReclusos(
                        ControladorSistema.operaciones.getListaRecluso()
                );
                break;
            }
        }

        if (sw == 0) {
            msjLable.setText("Celda no encontrada");
        }
    }//GEN-LAST:event_CambiarCeldaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reclusos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reclusos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reclusos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reclusos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reclusos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarCeldaBtn;
    private javax.swing.JButton btnBuscarCelda;
    private javax.swing.JButton btnBuscarDelito;
    private javax.swing.JButton btnCambiaCelda;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCeldaActual;
    private javax.swing.JLabel lblNuevaCelda;
    private javax.swing.JLabel msjLable;
    private javax.swing.JTable tablaReclusos;
    private javax.swing.JTextField txtBuscarCelda;
    private javax.swing.JTextField txtBuscarDelito;
    private javax.swing.JTextField txtCeldaActual;
    private javax.swing.JTextField txtNuevaCelda;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(
                    getClass().getResource("/Imagenes/reclu1.jpg")
            ).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
