/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCarcel;

import carcelConsola.Recluso;
import carcelConsola.Visita;
import controlador.ControladorSistema;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yo
 */
public class Visitas extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    /**
     * Creates new form Visitas
     */
    public Visitas() {
        this.setContentPane(fondo);
        initComponents();
        //llamamos al controlador que tendra la lista
        cargarTablaReclusos(ControladorSistema.operaciones.getListaVisita());
        //labels y text fields que al inicio estaran invicibles
        lblCiVisitanteVerificacion.setVisible(false);
        txtCiVisitanteVerificacion.setVisible(false);
        lblCiReclusoVerificacion.setVisible(false);
        txtCiReclusoVerificacion.setVisible(false);
        btnVerificarVisita.setVisible(false);

        lblCIvisi.setVisible(false);
        txtVisi.setVisible(false);
        lblSalida.setVisible(false);
        txtSalida.setVisible(false);
        confirmarBtn.setVisible(false);

        lblCiVisita.setVisible(false);
        txtCiVisitar.setVisible(false);
        realizarVisitaOsiBtn.setVisible(false);
    }

    //metodo para cargar la tabla y que guarde cada dato en cada columna y fila
    private void cargarTablaReclusos(List<Visita> lista) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI");
        modelo.addColumn("Parentesco");
        modelo.addColumn("Fecha");

        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Recluso");
        modelo.addColumn("Verificación");
        modelo.addColumn("Estado");

        for (Visita a : lista) {
            modelo.addRow(new Object[]{
                a.getNombre(),
                a.getEdad(),
                a.getCi(),
                a.getParentesco(),
                a.getFecha(),
                a.getFechaSa(),
                a.getRecluso(),
                a.getVerificacion(),
                a.getEstado()});
        }
        //pasamos los datos a la tabla, seteando :D
        tablaVisitas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVisitas = new javax.swing.JTable();
        msjLabel = new javax.swing.JLabel();
        btnVerTodos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFechaBuscar = new javax.swing.JTextField();
        btnBuscarPorFecha = new javax.swing.JButton();
        txtCiVisitanteVerificacion = new javax.swing.JTextField();
        lblCiVisitanteVerificacion = new javax.swing.JLabel();
        btnRealizarVerificacion = new javax.swing.JButton();
        txtCiReclusoVerificacion = new javax.swing.JTextField();
        lblCiReclusoVerificacion = new javax.swing.JLabel();
        btnVerificarVisita = new javax.swing.JButton();
        btnVisitarRecluso = new javax.swing.JButton();
        lblCiVisita = new javax.swing.JLabel();
        txtCiVisitar = new javax.swing.JTextField();
        realizarVisitaOsiBtn = new javax.swing.JButton();
        btnRegistrarSa = new javax.swing.JButton();
        lblCIvisi = new javax.swing.JLabel();
        txtVisi = new javax.swing.JTextField();
        lblSalida = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        confirmarBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("LISTA DE VISITAS");

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "CI.", "Parentesco", "Fecha", "Fecha de salida", "Recluso", "Verificacion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaVisitas);

        msjLabel.setForeground(new java.awt.Color(255, 255, 0));
        msjLabel.setText("msj");

        btnVerTodos.setText("ACTUALIZAR");
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("VER VISITAS POR FECHA");

        btnBuscarPorFecha.setText("MOSTRAR");
        btnBuscarPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorFechaActionPerformed(evt);
            }
        });

        txtCiVisitanteVerificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiVisitanteVerificacionActionPerformed(evt);
            }
        });

        lblCiVisitanteVerificacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCiVisitanteVerificacion.setForeground(new java.awt.Color(255, 255, 0));
        lblCiVisitanteVerificacion.setText("CI. Visitante :");

        btnRealizarVerificacion.setText("REALIZAR VERIFICACION");
        btnRealizarVerificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVerificacionActionPerformed(evt);
            }
        });

        lblCiReclusoVerificacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCiReclusoVerificacion.setForeground(new java.awt.Color(255, 255, 0));
        lblCiReclusoVerificacion.setText("CI. Recluso");

        btnVerificarVisita.setText("VERIFICAR");
        btnVerificarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarVisitaActionPerformed(evt);
            }
        });

        btnVisitarRecluso.setText("VISITAR RECLUSO");
        btnVisitarRecluso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitarReclusoActionPerformed(evt);
            }
        });

        lblCiVisita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCiVisita.setForeground(new java.awt.Color(255, 255, 0));
        lblCiVisita.setText("Por favor ingrese su CI.");

        txtCiVisitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiVisitarActionPerformed(evt);
            }
        });

        realizarVisitaOsiBtn.setText("REALIZAR VISITA");
        realizarVisitaOsiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVisitaOsiBtnActionPerformed(evt);
            }
        });

        btnRegistrarSa.setText("REGISTRAR SALIDA");
        btnRegistrarSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSaActionPerformed(evt);
            }
        });

        lblCIvisi.setForeground(new java.awt.Color(255, 255, 0));
        lblCIvisi.setText("CI del visitante:");

        lblSalida.setForeground(new java.awt.Color(255, 255, 0));
        lblSalida.setText("Fecha de salida:");

        confirmarBtn.setText("CONFIRMAR SALIDA");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRealizarVerificacion)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCiVisitanteVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCiVisitanteVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblCiReclusoVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCiReclusoVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscarPorFecha)
                                    .addGap(336, 336, 336)
                                    .addComponent(btnVerificarVisita)
                                    .addGap(0, 129, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(186, 186, 186)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerTodos))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisitarRecluso)
                            .addComponent(btnRegistrarSa))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCiVisita, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(lblCIvisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCiVisitar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtVisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(txtSalida, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(realizarVisitaOsiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(confirmarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 311, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnVerTodos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRealizarVerificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCiVisitanteVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCiVisitanteVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiReclusoVerificacion)
                            .addComponent(txtCiReclusoVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBuscarPorFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerificarVisita)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisitarRecluso)
                    .addComponent(lblCiVisita)
                    .addComponent(txtCiVisitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realizarVisitaOsiBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCIvisi)
                                    .addComponent(txtVisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnRegistrarSa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalida)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmarBtn)
                        .addGap(22, 22, 22)))
                .addComponent(msjLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        // TODO add your handling code here:
        //cada que li piques en actualizar volvera a ocultar algunos botones y labels y limpiara los campos
        lblCiVisitanteVerificacion.setVisible(false);
        txtCiVisitanteVerificacion.setVisible(false);
        lblCiReclusoVerificacion.setVisible(false);
        txtCiReclusoVerificacion.setVisible(false);
        btnVerificarVisita.setVisible(false);

        lblCIvisi.setVisible(false);
        txtVisi.setVisible(false);
        lblSalida.setVisible(false);
        txtSalida.setVisible(false);
        confirmarBtn.setVisible(false);

        lblCiVisita.setVisible(false);
        txtCiVisitar.setVisible(false);
        realizarVisitaOsiBtn.setVisible(false);

        txtFechaBuscar.setText("");
        msjLabel.setText("");

        //actualiza la tabla en caso de ser necesario
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI");
        modelo.addColumn("Parentesco");
        modelo.addColumn("Fecha");

        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Recluso");
        modelo.addColumn("Verificación");
        modelo.addColumn("Estado");

        for (Visita a : ControladorSistema.operaciones.getListaVisita()) {
            Object[] fila = {
                a.getNombre(), a.getEdad(), a.getCi(),
                a.getParentesco(), a.getFecha(), a.getFechaSa(), a.getRecluso(), a.getVerificacion(),a.getEstado()
            };
            modelo.addRow(fila);
        }
        tablaVisitas.setModel(modelo);
    }//GEN-LAST:event_btnVerTodosActionPerformed

    private void btnBuscarPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorFechaActionPerformed
        // TODO add your handling code here:
        String fechaBuscada = txtFechaBuscar.getText();
        int sw = 0;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("CI");
        modelo.addColumn("Parentesco");
        modelo.addColumn("Fecha");

        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Recluso");
        modelo.addColumn("Verificación");
        modelo.addColumn("Estado");

        for (Visita v : ControladorSistema.operaciones.getListaVisita()) {
            if (v.getFecha().equalsIgnoreCase(fechaBuscada)) {
                sw = 1;
                Object[] fila = {
                    v.getNombre(), v.getEdad(), v.getCi(), v.getParentesco(),
                    v.getFecha(), v.getFechaSa(), v.getRecluso(), v.getVerificacion(),v.getEstado()
                };
                modelo.addRow(fila);
            }
        }
        if (sw == 0) {
            msjLabel.setText("No se encontro visitas para esa fecha");
        } else {
            tablaVisitas.setModel(modelo);
            msjLabel.setText("");
        }

    }//GEN-LAST:event_btnBuscarPorFechaActionPerformed

    private void txtCiVisitanteVerificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiVisitanteVerificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiVisitanteVerificacionActionPerformed

    private void btnRealizarVerificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVerificacionActionPerformed
        // TODO add your handling code here:
        //al apretar el bton realizar verificacion apareceran los botones y labels ocultos
        lblCiVisitanteVerificacion.setVisible(true);
        txtCiVisitanteVerificacion.setVisible(true);
        lblCiReclusoVerificacion.setVisible(true);
        txtCiReclusoVerificacion.setVisible(true);
        btnVerificarVisita.setVisible(true);
    }//GEN-LAST:event_btnRealizarVerificacionActionPerformed

    private void btnVerificarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarVisitaActionPerformed
        // TODO add your handling code here:
        String ciVisitante = txtCiVisitanteVerificacion.getText();
        String ciRecluso = txtCiReclusoVerificacion.getText();
        int swv = 0, swr = 0;

        for (Visita v : ControladorSistema.operaciones.getListaVisita()) {
            if (v.getCi().equalsIgnoreCase(ciVisitante)) {
                swv = 1;
                for (Recluso r : ControladorSistema.operaciones.getListaRecluso()) {
                    if (r.getNombre().equalsIgnoreCase(v.getRecluso()) && r.getCi().equalsIgnoreCase(ciRecluso)) {
                        swr = 1;
                        v.setVerificacion("APROBADO");
                        msjLabel.setText("Verificación exitosa, puede realizar la visita.");
                        cargarTablaReclusos(ControladorSistema.operaciones.getListaVisita());

                    }
                }
                if (swr == 0) {
                    v.setVerificacion("RECHAZADO");
                    msjLabel.setText("Recluso no encontrado, verificacion rechazada");
                }

            }
        }
        if (swv == 0) {
            msjLabel.setText("CI. de visitante no encontrado");

        }

    }//GEN-LAST:event_btnVerificarVisitaActionPerformed

    private void btnVisitarReclusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitarReclusoActionPerformed
        // TODO add your handling code here:
        //al apretar el boton visitar recluso aparecen los botones y labels ocultos
        lblCiVisita.setVisible(true);
        txtCiVisitar.setVisible(true);
        realizarVisitaOsiBtn.setVisible(true);

    }//GEN-LAST:event_btnVisitarReclusoActionPerformed

    private void realizarVisitaOsiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVisitaOsiBtnActionPerformed
        // TODO add your handling code here:
        //este metodo realiza la visita pero preguntando si el visitante hizo o no hizo la verificacio
        int sw = 0;
        String ciVisitante = txtCiVisitar.getText();
        for (Visita v : ControladorSistema.operaciones.getListaVisita()) {
            if (v.getCi().equalsIgnoreCase(ciVisitante)) {
                sw = 1;
                if (v.getVerificacion().equalsIgnoreCase("APROBADO")) {
                    JOptionPane.showMessageDialog(this,
                            "Visita realizada con exito!\n"
                            + "Visitante: " + v.getNombre() + "\n"
                            + "Recluso: " + v.getRecluso() + "\n"
                            + "Parentesco: " + v.getParentesco() + "\n"
                            + "Fecha: " + v.getFecha());
                    //una vez que el visitante realizo la visita, se lo elimina de la lista
                    v.setEstado("DENTRO");
                    break;
                } else {
                    if (v.getVerificacion().equalsIgnoreCase("PENDIENTE")) {
                        msjLabel.setText("PORFAVOR REALICE LA VERIFICACION!");
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "La visita fue rechazada.\nDebe registrarse nuevamente si desea volver a intentarlo.");
                        ControladorSistema.operaciones.getListaVisita().remove(v);
                        break;
                    }
                }
            }
        }
        if (sw == 0) {
            msjLabel.setText("Usted no se encuentra registrado en el sistema");
        }

    }//GEN-LAST:event_realizarVisitaOsiBtnActionPerformed

    private void txtCiVisitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiVisitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiVisitarActionPerformed

    private void btnRegistrarSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSaActionPerformed
        // TODO add your handling code here:
        lblCIvisi.setVisible(true);
        txtVisi.setVisible(true);
        lblSalida.setVisible(true);
        txtSalida.setVisible(true);
        confirmarBtn.setVisible(true);
    }//GEN-LAST:event_btnRegistrarSaActionPerformed

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        // TODO add your handling code here:
        String ci = txtVisi.getText();
        int sw = 0;

        for (Visita v : ControladorSistema.operaciones.getListaVisita()) {

            if (v.getCi().equalsIgnoreCase(ci)) {
                sw = 1;

                if (v.getEstado().equalsIgnoreCase("DENTRO")) {

                    String fechaActual = LocalDate.now()
                            .format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

                    v.setFechaSa(fechaActual);
                    v.setEstado("SALIO");

                    msjLabel.setText("Salida registrada correctamente");
                    cargarTablaReclusos(ControladorSistema.operaciones.getListaVisita());

                } else {
                    msjLabel.setText("El visitante no se encuentra dentro");
                }

                break;
            }
        }

        if (sw == 0) {
            msjLabel.setText("Visitante no encontrado");
        }
    }//GEN-LAST:event_confirmarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorFecha;
    private javax.swing.JButton btnRealizarVerificacion;
    private javax.swing.JButton btnRegistrarSa;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton btnVerificarVisita;
    private javax.swing.JButton btnVisitarRecluso;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCIvisi;
    private javax.swing.JLabel lblCiReclusoVerificacion;
    private javax.swing.JLabel lblCiVisita;
    private javax.swing.JLabel lblCiVisitanteVerificacion;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel msjLabel;
    private javax.swing.JButton realizarVisitaOsiBtn;
    private javax.swing.JTable tablaVisitas;
    private javax.swing.JTextField txtCiReclusoVerificacion;
    private javax.swing.JTextField txtCiVisitanteVerificacion;
    private javax.swing.JTextField txtCiVisitar;
    private javax.swing.JTextField txtFechaBuscar;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtVisi;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/visi4.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
